[features]
resolution = true
skip-lint = false

[programs.devnet]
citylight_audit = "AbgBg2HV8yVGUmtuZKUpifxitbhWwQ1qgrH4m158LSUx"

[provider]
cluster = "devnet"
wallet = ".secrets/publisher.json"

[scripts]
test = "pnpm test:chain"
