import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Detection={box:number[];class:string;track_id:number;stopped:boolean;approach:string|null;score_milli:number};
type Frame={time_ms:number;detections:Detection[];approaches:Record<string,{queued:number;moving:number}>;inference_ms:number;decision:{phase:string;lamps:Record<string,string>;remaining_ms:number;reason:string;fallback:boolean;transition:boolean}};
type Run={metadata:{run_id:string;width:number;height:number;duration_ms:number;model_sha256:string;policy_hash:string};frames:Frame[];evidence:{hash:string;bundle:{sequence:number;observation:Frame}}[];processing_ms:number};
type Chain={status:string;program_id?:string;authority?:string;registry?:string;receipts:{sequence:number;signature:string;address:string;hash:string;status:string}[];verification?:{valid:boolean;tampered_rejected:boolean;unauthorized_rejected?:boolean}};
const short=(s?:string)=>s?`${s.slice(0,8)}…${s.slice(-6)}`:'—';
const explorer=(address:string)=>`https://explorer.solana.com/address/${address}?cluster=devnet`;
function App(){
 const [run,setRun]=useState<Run>();const [chain,setChain]=useState<Chain>({status:'not_published',receipts:[]});const [time,setTime]=useState(0);const [playing,setPlaying]=useState(false);const [job,setJob]=useState<any>({status:'idle'});const [error,setError]=useState('');const [zones,setZones]=useState<Record<string,number[][]>>({});const [inspect,setInspect]=useState<number>();const video=useRef<HTMLVideoElement>(null);const canvas=useRef<HTMLCanvasElement>(null);
 const load=async()=>{try{const r=await fetch('/api/run');if(r.ok)setRun(await r.json());const c=await fetch('/api/chain');if(c.ok)setChain(await c.json());const z=await fetch('/api/calibration');if(z.ok)setZones((await z.json()).zones);}catch{setError('Backend unavailable. Start the local service.');}};
 useEffect(()=>{void load();const id=setInterval(async()=>{try{const s=await fetch('/api/status');if(!s.ok)throw Error();const data=await s.json();setJob(data.job);if(data.job.status==='error')setError(data.job.error);if(data.run_ready)void load();}catch{setError('Backend unavailable. Start the local service.');}},2500);return()=>clearInterval(id);},[]);
 const frame=run?.frames.reduce((best,f)=>f.time_ms<=time?f:best,run.frames[0]);
 useEffect(()=>{const c=canvas.current;if(!c||!run||!frame)return;c.width=run.metadata.width;c.height=run.metadata.height;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);ctx.lineWidth=3;ctx.font='22px monospace';
 Object.entries(zones).forEach(([name,points])=>{ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x*c.width,y*c.height):ctx.moveTo(x*c.width,y*c.height));ctx.closePath();ctx.fillStyle=name==='A'?'#30dbc715':'#e9b86d15';ctx.fill();ctx.strokeStyle=name==='A'?'#30dbc780':'#e9b86d80';ctx.stroke();});
 frame.detections.forEach(d=>{const [x,y,x2,y2]=d.box;ctx.strokeStyle=d.stopped?'#ffc86b':'#68f2d2';ctx.strokeRect(x,y,x2-x,y2-y);const label=`${d.class} #${d.track_id}${d.stopped?' · stopped':''}`;ctx.fillStyle='#0b1215dd';ctx.fillRect(x,Math.max(0,y-29),ctx.measureText(label).width+12,29);ctx.fillStyle=ctx.strokeStyle;ctx.fillText(label,x+6,Math.max(23,y-7));});},[frame,run,zones]);
 const toggle=async()=>{try{if(!video.current)return;if(video.current.paused)await video.current.play();else video.current.pause();}catch{setError('Video playback failed. Check the downloaded asset.');}};
 const start=async()=>{setError('');try{const r=await fetch('/api/process',{method:'POST'});if(!r.ok)throw Error((await r.json()).detail);setJob(await r.json());}catch(e){setError(String(e));}};
 const currentEvidence=run?.evidence.filter(e=>e.bundle.observation.time_ms<=time).at(-1);const selected=run?.evidence.find(e=>e.bundle.sequence===(inspect??currentEvidence?.bundle.sequence));const receipt=chain.receipts.find(r=>r.sequence===selected?.bundle.sequence);
 return <div className="app"><aside><a className="brand" href="/"><span className="mark">▥</span> CityLight<span>AI</span></a><div className="sidebar-label">OPERATOR WORKSPACE</div><div className="nav active"><span>◉</span> Intersection Lab</div><a className="nav" href="#audit"><span>◇</span> Decision evidence</a><div className="sidebar-bottom"><span className="dot"/> Single-intersection MVP<br/><small>Recorded video · Devnet<br/>No physical signal actuation</small></div></aside><main><header><div><div className="eyebrow">CITYLIGHTAI / INTERSECTION LAB</div><h1>See traffic. Explain every decision.</h1><p>Camera-based perception with an independently verifiable audit trail.</p></div><div className="demo-badge"><span className="dot"/> DEMO ENVIRONMENT</div></header>
 <div className="pipeline"><span>01 <b>Video perception</b></span><i>→</i><span>02 <b>Queue estimate</b></span><i>→</i><span>03 <b>Adaptive recommendation</b></span><i>→</i><span>04 <b>Solana evidence</b></span></div>
 {error&&<div className="error" role="alert">{error}</div>}
 <section className="metrics"><div><small>VISIBLE VEHICLES</small><strong>{frame?.detections.length??'—'}</strong><span>Current sampled frame</span></div><div><small>ESTIMATED STOPPED</small><strong>{frame?Object.values(frame.approaches).reduce((s,a)=>s+a.queued,0):'—'}</strong><span>Tracked within approach regions</span></div><div><small>RECOMMENDED PHASE</small><strong className="phase-title">{frame?.decision.phase.replaceAll('_',' ')??'Awaiting inference'}</strong><span>Virtual two-phase controller</span></div><div><small>DEVNET RECORDS</small><strong>{chain.receipts.filter(r=>r.status==='finalized').length}<em> / {run?.evidence.length??0}</em></strong><span>{chain.status==='not_published'?'Not published yet':'Finalized, independently readable'}</span></div></section>
 <div className="workspace"><section className="panel video-panel"><div className="panel-heading"><div><h2>Intersection observation</h2><p>Licensed reference footage · location as credited below</p></div><span className="tag">RECORDED VIDEO</span></div><div className="video-wrap"><video ref={video} src="/api/video" muted playsInline preload="metadata" onTimeUpdate={e=>setTime(Math.round(e.currentTarget.currentTime*1000))} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)}/><canvas ref={canvas}/><div className="video-overlay"><span className="dot"/> {run?'COMPUTED DETECTIONS · REPLAY':'INFERENCE REQUIRED'}</div></div><div className="playback"><button onClick={toggle} disabled={!run}>{playing?'❚❚ Pause':'▶ Play demo'}</button><input aria-label="Video position" type="range" min={0} max={run?.metadata.duration_ms??1} step={100} value={time} disabled={!run} onChange={e=>{const t=Number(e.target.value);setTime(t);if(video.current)video.current.currentTime=t/1000;}}/><span>{(time/1000).toFixed(1)}s / {((run?.metadata.duration_ms??0)/1000).toFixed(1)}s</span></div><div className="legend"><span><i className="green"/> Moving / newly tracked</span><span><i className="amber"/> Estimated stopped</span><span>YOLOX · CPU inference · {frame?.inference_ms??'—'} ms/sample</span></div></section>
 <section className="panel decision-panel"><div className="panel-heading"><div><h2>Adaptive recommendation</h2><p>Demand-responsive, bounded timing</p></div><span className={`tag ${frame?.decision.fallback?'warn':''}`}>{frame?.decision.fallback?'FALLBACK':'RECOMMENDATION'}</span></div><div className="approaches">{['A','B'].map(k=><div className="approach" key={k}><div className={`signal ${frame?.decision.lamps[k]??'red'}`}><i/><i/><i/></div><div><h3>Approach {k}</h3><p><b>{frame?.approaches[k]?.queued??'—'}</b> estimated stopped · <b>{frame?.approaches[k]?.moving??'—'}</b> moving</p></div><span>{frame?.decision.lamps[k]??'—'}</span></div>)}</div><div className="reason"><div className="eyebrow">WHY THIS TIMING?</div><p>{frame?.decision.reason??'Run the actual vehicle detector to generate traffic observations and recommendations.'}</p></div><div className="constraints"><span>✓ Minimum / maximum green</span><span>✓ Yellow + all-red clearance</span><span>✓ Maximum service wait</span><span>✓ Stale-data fallback</span></div><p className="notice">Signals shown here are recommendations. Recorded traffic does not react to them. Pedestrian and turn phases are outside this simplified model.</p></section></div>
 <section className="panel audit-panel" id="audit"><div className="panel-heading"><div><div className="eyebrow">SOLANA / DEVNET</div><h2>A decision you can check</h2><p>Verify publisher authorization, policy and evidence integrity.</p></div><span className={`tag ${receipt?'':'warn'}`}>{receipt?receipt.status.toUpperCase():'PENDING PUBLICATION'}</span></div><div className="audit-grid"><div><small>PROGRAM</small>{chain.program_id?<a href={explorer(chain.program_id)} target="_blank" rel="noreferrer">{short(chain.program_id)} ↗</a>:<span>Not deployed</span>}<small>APPROVED POLICY COMMITMENT</small><code>{short(run?.metadata.policy_hash)}</code></div><div><small>EVIDENCE SHA-256</small><code>{short(selected?.hash)}</code><small>RECEIPT ACCOUNT</small>{receipt?<a href={explorer(receipt.address)} target="_blank" rel="noreferrer">{short(receipt.address)} ↗</a>:<span>No on-chain receipt yet</span>}</div><div><small>INDEPENDENT VERIFICATION</small><span>{chain.verification?.valid?'✓ Published evidence verified':'Not verified yet'}</span><span>{chain.verification?.tampered_rejected?'✓ Modified evidence rejected':'Tamper test not run'}</span><p className="notice">Integrity and authorization checks do not prove that the camera or AI observations are correct.</p></div></div><div className="receipt-list">{run?.evidence.map(e=><button key={e.bundle.sequence} className={selected?.bundle.sequence===e.bundle.sequence?'selected':''} onClick={()=>setInspect(e.bundle.sequence)}>#{e.bundle.sequence} · {(e.bundle.observation.time_ms/1000).toFixed(1)}s <span>{chain.receipts.some(r=>r.sequence===e.bundle.sequence)?'↗':'○'}</span></button>)}</div>{selected&&<a className="download" href={`/api/evidence/${selected.bundle.sequence}`} target="_blank" rel="noreferrer">Open evidence bundle ↗</a>}</section>
 <section className="inference"><div><h3>Reproduce the observation</h3><p>Runs the local model, then publishes the resulting decisions to Devnet. Playback replays timestamped output.</p>{job.publication_error&&<p role="status">Publication pending: {job.publication_error}</p>}</div><button onClick={start} disabled={job.status==='running'||job.status==='publishing'}>{job.status==='running'?`Processing ${((job.processed_ms??0)/1000).toFixed(1)}s…`:job.status==='publishing'?'Publishing to Devnet…':'Run detection & publish ↗'}</button></section>
 <footer><span>Reference video: Tom Fisk / Pexels · <a href="https://www.pexels.com/video/3052883/" target="_blank" rel="noreferrer">source & credit</a> · <a href="https://www.pexels.com/license/" target="_blank" rel="noreferrer">license</a></span><span>Accelerated demo timings. No real-world deployment.</span></footer>
 </main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
